version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: golang:1.26-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "go run ./cmd/bot"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/bot_db?sslmode=disable"
    depends_on:
      - postgres

volumes:
  postgres_data: